apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: <name_here>
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: helm
  helm:
    repo: oci://europe-west2-docker.pkg.dev/playpen-0mybl5/helm-charts
    chart: istio
    version: <version>
    releaseName: <release_name>
    includeCRDs: true
    namespace: <namespace>
    auth: gcpserviceaccount
    gcpServiceAccountEmail: <GCP_service_acount>