resources:
- add-ons.yaml


helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.5.3
  releaseName: my-cert-manager
  namespace: cert-manager
- name: hello-chart
  repo: oci://europe-west2-docker.pkg.dev/playpen-0mybl5/istio-helm-pp/hello-chart
  version: "0.1.0"
  releaseName: hello-chart
  namespace: default