resources:
- ../../charts

patches:
- target:
    kind: RootSync
  patch: |-
    - op: replace
      path: /spec/helm/gcpServiceAccountEmail
      value: playpen-0mybl5-sa@playpen-0mybl5.iam.gserviceaccount.com

- target:
    name: istio
  path: values/istio.yaml
- target:
    name: cert-manager
  path: values/cert-manager.yaml